homework4/file_searcher/urls.py
from django.urls import path
from file_searcher.views import (
    AddFileView,
    FileUploadListView,
    FileUploadDeleteView,
    FileAnalyzerListView,
    FileAnalyzerView,
    FileAnalyzerDetailView,
    FileAnalyzerDeleteView,
    RepeatFileAnalysisView,
)

urlpatterns = [
    path("add_file/", AddFileView.as_view(), name="add-file"),
    path("list/", FileUploadListView.as_view(), name="file-upload-list"),
    path("delete/<int:pk>", FileUploadDeleteView.as_view(), name="file-upload-delete"),
    path("analyze/<int:pk>", FileAnalyzerView.as_view(), name="file-analyze"),
    path(
        "analyze/<int:pk>/repeat",
        RepeatFileAnalysisView.as_view(),
        name="file-analyze-repeat",
    ),
    path(
        "analyze/<int:pk>/list",
        FileAnalyzerListView.as_view(),
        name="file-analyze-list",
    ),
    path(
        "analyze/<int:pk>/view",
        FileAnalyzerDetailView.as_view(),
        name="file-analyzer-view",
    ),
    path(
        "analyze/<int:pk>/delete",
        FileAnalyzerDeleteView.as_view(),
        name="file-analyzer-delete",
    ),
]

homework4/google_services/urls.py
from django.contrib import admin
from django.urls import path, include

from google_services.views import home, health


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home-page"),
    path("files/", include("file_searcher.urls")),
    path("users/", include("users.urls")),
    path("health/", health, name="health"),
]

homework4/users/urls.py
from django.urls import path

from users.views import (
    RegisterView,
    CustomLoginView,
    CustomLogoutView,
    UserDetailView,
    UserUpdateView,
    UserDeleteView,
)


urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("users/<int:pk>", UserDetailView.as_view(), name="user-view"),
    path("users/<int:pk>/update", UserUpdateView.as_view(), name="user-update"),
    path("users/<int:pk>/delete", UserDeleteView.as_view(), name="user-delete"),
]

homework4/file_searcher/models.py
from django.db import models
from django.utils import timezone
from users.models import User


class FileUpload(models.Model):
    class Status(models.TextChoices):
        PROCESSING = "processing"
        FAILED = "failed"
        SUCCESS = "success"
        FAILED_DELETION = "failed_deletion"

    file_name = models.CharField(max_length=256)
    file_path = models.CharField(max_length=64, blank=True, null=True)
    upload_time = models.DateTimeField(default=timezone.now())
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    status = models.CharField(
        choices=Status.choices, default=Status.PROCESSING, max_length=30
    )

    objects = models.Manager()

    def __str__(self):
        return self.file_name


class FileAnalyzer(models.Model):
    class Status(models.TextChoices):
        PROCESSING = "processing"
        FAILED = "failed"
        SUCCESS = "success"
        PARTIAL_SUCCESS = "partial_success"
        DOWNLOAD_FAIL = "download_file_failed"
        SAVE_LOCAL_FILE_FAIL = "save_local_file_failed"
        EXTRACT_TEXT_FAIL = "extract_text_failed"

    file = models.ForeignKey(
        FileUpload, on_delete=models.CASCADE, related_name="file_upload"
    )
    error_analyzer = models.CharField(max_length=1024, blank=True, null=True)
    error_classifier = models.CharField(max_length=1024, blank=True, null=True)
    sentiment = models.CharField(max_length=2048, blank=True, null=True)
    categories = models.CharField(max_length=2048, blank=True, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    error = models.CharField(max_length=1024, blank=True, null=True)
    status = models.CharField(
        choices=Status.choices, default=Status.PROCESSING, max_length=30
    )

    objects = models.Manager()

homework4/file_searcher/forms.py
from django import forms


class FileUploadForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        uploaded_file = self.cleaned_data["file"]
        if uploaded_file.content_type != "application/pdf":
            self.add_error("file", "Only PDF files are accepted")

        return uploaded_file

homework4/file_searcher/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db.models import F
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import ListView, TemplateView, DetailView
from django.views.generic.edit import FormView, DeleteView

from file_searcher.forms import FileUploadForm
from file_searcher.models import FileUpload, FileAnalyzer
from file_searcher.tasks import (
    analyze_file,
)


class AddFileView(LoginRequiredMixin, FormView):
    template_name = "file_searcher/add_file.html"
    form_class = FileUploadForm
    success_url = reverse_lazy("add-file")

    def form_valid(self, form):
        uploaded_file = self.request.FILES.get("file")
        temp_file_path = default_storage.save(
            f"tmp/{uploaded_file.name}", ContentFile(uploaded_file.read())
        )
        file_up = FileUpload(
            file_name=uploaded_file.name,
            user=self.request.user,
            file_path=temp_file_path,
            status=FileUpload.Status.SUCCESS,
        )
        file_up.save()
        messages.success(self.request, "File uploaded.")
        return super().form_valid(form)


class FileUploadListView(LoginRequiredMixin, ListView):
    model = FileUpload
    template_name = "file_searcher/list.html"

    def get_queryset(self):
        return (
            FileUpload.objects.select_related("user")
            .filter(user=self.request.user)
            .order_by(F("upload_time").desc())
        )


class FileUploadDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "file_searcher/delete.html"
    model = FileUpload
    success_url = reverse_lazy("file-upload-list")

    def get_object(self, queryset=None):
        return get_object_or_404(
            FileUpload, pk=self.kwargs.get("pk"), user=self.request.user
        )

    def form_valid(self, form):
        self.object = self.get_object()
        default_storage.delete(self.object.file_path)
        self.object.delete()
        messages.info(self.request, "File deleted")
        return HttpResponseRedirect(self.get_success_url())


class FileAnalyzerListView(LoginRequiredMixin, ListView):
    model = FileAnalyzer
    template_name = "file_searcher/analyzer/list.html"

    def get_queryset(self):
        return (
            FileAnalyzer.objects.select_related("file")
            .filter(file__user=self.request.user, file__id=self.kwargs.get("pk"))
            .order_by(F("created_at").desc())
        )


class FileAnalyzerView(LoginRequiredMixin, TemplateView):

    def get(self, *args, **kwargs):
        file = get_object_or_404(FileUpload, id=self.kwargs.get("pk"))
        file_analyzer = FileAnalyzer(file=file)
        file_analyzer.save()

        analyze_file.delay(file_analyzer.id)
        messages.info(self.request, "File sent for analysis")
        return HttpResponseRedirect(reverse_lazy("file-upload-list"))


class RepeatFileAnalysisView(LoginRequiredMixin, TemplateView):

    def get(self, *args, **kwargs):
        file_analyzer = get_object_or_404(FileAnalyzer, id=self.kwargs.get("pk"))
        analyze_file.delay(file_analyzer.id)
        messages.info(self.request, "File sent for analysis")
        return HttpResponseRedirect(
            reverse_lazy("file-analyze-list", kwargs={"pk": file_analyzer.file.id})
        )


class FileAnalyzerDetailView(LoginRequiredMixin, DetailView):
    model = FileAnalyzer
    template_name = "file_searcher/analyzer/view.html"

    def get_object(self, queryset=None):
        return get_object_or_404(FileAnalyzer, id=self.kwargs.get("pk"))


class FileAnalyzerDeleteView(LoginRequiredMixin, DeleteView):
    template_name = "file_searcher/analyzer/delete.html"
    model = FileAnalyzer

    def get_object(self, queryset=None):
        return get_object_or_404(
            FileAnalyzer, pk=self.kwargs.get("pk"), file__user=self.request.user
        )

    def form_valid(self, form):
        success_url = reverse_lazy(
            "file-analyze-list", kwargs={"pk": self.object.file.id}
        )
        self.object.delete()
        return HttpResponseRedirect(success_url)

homework4/templates/file_searcher/add_file.html
{% extends "index.html" %}

{% block content %}
<div class="container mt-5">
    <div class="text-center">
        {% include "utils/messages.html" %}
    </div>
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5>Upload File</h5>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group mb-3 mt-3">
                            <label for="id_file">File</label>
                            {{ form.file }}
                            {% if form.file.errors %}
                                <div class="alert alert-danger mt-2">
                                    {% for error in form.file.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-primary">Upload</button>
                        <a href="{% url 'home-page' %}" class="btn btn-secondary">Back to home</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

homework4/templates/file_searcher/delete.html
{% extends "index.html" %}

{% block content %}
<div class="container mt-5">
    <div class="text-center">
        {% include "utils/messages.html" %}
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    Confirm Delete
                </div>
                <div class="card-body">
                    <h5 class="card-title">Are you sure you want to delete this file?</h5>
                    <p>This action cannot be undone and will be deleted permanently from Google Drive</p>
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            {% if object %}
                            <button type="submit" class="btn btn-danger">Yes, delete the file</button>
                            {% endif %}
                            <a href="{% url 'file-upload-list' %}" class="btn btn-secondary">Back</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

homework4/templates/file_searcher/list.html
{% extends "index.html" %}

{% block content %}
<div class="text-center">
    {% include "utils/messages.html" %}
</div>
<div class="container mt-5">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>File upload list</h2>
    </div>
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">File name</th>
                    <th scope="col">File path</th>
                    <th scope="col">User</th>
                    <th scope="col">Status</th>
                    <th scope="col">Uploaded at</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for file_upload in object_list %}
                <tr>
                    <td>{{ file_upload.id }}</td>
                    <td>{{ file_upload.file_name }}</td>
                    <td>{{ file_upload.file_path }}</td>
                    <td>{{ file_upload.user }}</td>
                    <td>{{ file_upload.status }}</td>
                    <td>{{ file_upload.upload_time }}</td>
                    <td>
                        <a href="{% url 'file-analyze' file_upload.id %}" class="btn btn-success">Analyze</a>
                        <a href="{% url 'file-analyze-list' file_upload.id %}" class="btn btn-info">View Analysis</a>
                        <a href="{% url 'file-upload-delete' file_upload.id %}" class="btn btn-danger">Delete</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="4">No files uploaded.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

homework4/templates/file_searcher/view.html
{% extends "index.html" %}

{% block content %}
<div class="container mt-3">
    <div class="text-center">
        {% include "utils/messages.html" %}
    </div>
    <div class="card">
        <div class="card-header">
            Property Details
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">ID: {{ property.id }}</li>
            <li class="list-group-item">Starting Price: {{ property.startingPrice }}</li>
            <li class="list-group-item">End Price: {{ property.endPrice }}</li>
            <li class="list-group-item">Type: {{ property.type }}</li>
            <li class="list-group-item">Address: {{ property.address }}</li>
            <li class="list-group-item">Created At: {{ property.createdAt }}</li>
            <li class="list-group-item">Updated At: {{ property.updatedAt }}</li>
            <li class="list-group-item">Latitude: {{ property.lat|default:"inexistent" }}</li>
            <li class="list-group-item">Longitude: {{ property.long|default:"inexistent" }}</li>
            <li class="list-group-item">
                User: {{ property.user.email }}
            </li>
        </ul>
        <div class="card-footer">
            <a id="geo-location" {% if property %} href="{% url 'geo-location' property.id %}" {% else %} href="#" {% endif %} class="btn btn-info">Generate Coordinates</a>
            <a id="weather-button" {% if property %}  href="{% url 'weather-forecast' property.id %}" {% else %} href="#" {% endif %} class="btn btn-info">Weather Forecast</a>
            <button id="show-on-map" class="btn btn-info">Show on Map</button>
            <a {% if property %} href="{% url 'property-update' property.id %}" {% else %} href="#" {% endif %} class="btn btn-secondary">Update Property</a>
            <a {% if property %} href="{% url 'property-delete' property.id %}" {% else %} href="#" {% endif %} class="btn btn-danger">Delete Property</a>
        </div>
        <div id="weather"></div>
    </div>
</div>

{% if forecast %}
<div class="container mt-3">
    <h2>7 days Weather Forecast</h2>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Minimum Temperature (°C)</th>
                <th scope="col">Maximum Temperature (°C)</th>
                <th scope="col">Condition</th>
            </tr>
        </thead>
        <tbody>
            {% for day in forecast %}
            <tr>
                <td>{{ day.date }}</td>
                <td>{{ day.min_temp }}</td>
                <td>{{ day.max_temp }}</td>
                <td>{{ day.condition }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}


{% include "utils/map.html" %}

{% endblock %}

{% block scripts %}
<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
<script>
    $(document).ready(function(){

        $('#show-on-map').click(function (e){
            var url = "{% if property %} {% url 'show-map' property.id %} {% else %} '' {% endif %}";
            if(url !== ''){
                console.log(url);
                $.ajax({
                    url: url,
                    type: 'GET',
                    success: function(result) {
                        if(result.latitude && result.longitude){
                            var marker = L.marker([result.latitude, result.longitude]).addTo(map);
                            map.setView([result.latitude, result.longitude], 13);
                        }
                    },
                    error: function(error){
                        console.log('Error:', error);
                    }
                });
            }
        });
    });
</script>
{% endblock %}